#!/bin/bash -x
set -x
export curlimage=appropriate/curl
export jqimage=stedolan/jq

if [ -n ${docker_version} ]; then
  if [ `command -v curl` ]; then
    curl -sL https://releases.rancher.com/install-docker/${docker_version}.sh | sh
  elif [ `command -v wget` ]; then
    wget -qO- https://releases.rancher.com/install-docker/${docker_version}.sh | sh
  fi
fi

${register_command} ${node_roles}
